# Generated by Django 4.0.4 on 2022-05-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ctg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sayt.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=256),
        ),
    ]
