# Generated by Django 4.0.4 on 2022-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
